name: Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - "web/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_YWUq9bz3WHBgcl41XpyK8OUv
          vercel-project-id: prj_oM19AoeYhTxargcpfNmi2MGehXFM
          working-directory: ./web
          vercel-args: '--prod'
